### PR TITLE
Us85 t106 dialog box for topic

### PR DESCRIPTION
**Pull request by HalcyonAura**
To test: can you create new topics using add new topic button, do settings and create topic dialog look better/usable
* This PR encompasses tasks 106 and 116 due to their close overlap but individual extents of work needed

### CODE REVIEW

**Comment by HalcyonAura** [comment]
@namrathaov so the next task (see pr for it) fixes comments, and _should_ solve for the overflow you mentioned. If not please make a note of it when you review that pr. As for it retaining previous topic data, I've noticed it happening in the next task with comments as well. However, if you were to press submit without actually changing anything, no values from the previous topic are saved? So I wasn't too sure whether to fix or leave it as a happy accident (same with comments)

**Comment by namrathaov** [comment]
@HalcyonAura Sorry, I missed that. I'll keep in mind when reviewing your other PR.  When I was looking at your code, I wanted to note that this branch is based off a different branch I think? There's already a PR open for UI implementations branch to be merged.

**Comment by HalcyonAura** [comment]
@namrathaov I had US85 branch off the user story branch for UI_implementations because hadn't at the time merged that to master due to being incomplete. I believe I also pulled in master to US85 so it would have some recent work from backend (this is the UX branch which does have need for that, we'll likely need to remerge master) and then with each of my tasks I've been branching off of them continuously. Mostly this was to keep work continuity and some of the work was dependent on previous branches that hadn't been merged. That's most likely what you're seeing.

**Comment by kstrones** [comment]
Functionality is good. I like the new add topic dialog you created.

**Comment by HalcyonAura** [comment]
@namrathaov I updated this so the dialog box clears entries after submission, mind checking and seeing if you want more changes
@kstrones I edited this, you'll have to answer the review now instead of just commenting (sigh) to approve/request changes

**Pull request merged**
