### PR TITLE
Us39 t47 settings

### PR DESCRIPTION
**Pull request by kstrones**
Add the settings panel to the side panel and initial button controls for connecting to the backend.

### CODE REVIEW

**Comment by HalcyonAura** [comment]
Minor corrections would be to remove the border around the div holding the settings and the settings label ("settings"). While it's not important yet, we may need to reorganize the settings button to say settings when not in settings, and back when in settings, (and function as such). Aside from that I think it looks great, we can come up with actual settings and connect them next sprint

**Comment by namrathaov** [comment]
The setting options are very handy and fits the idea well. I personally feel it would be better if the settings title is noticeable or removed as we still have it at the bottom. As Cecilia pointed out, minor changes could be made, but right now, it does not hinder anything else. Looks good otherwise!

**Comment by kstrones** [comment]
That border was left from some testing to that has been removed. The label has been removed and settings button now changes text and follows the size of the menu being displayed.

**Comment by HalcyonAura** [comment]
Looks much better! I like it.

**Pull request merged**
